% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Project 1},
  pdfauthor={Chloe Chen \& Kangrui Liu},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Project 1}
\author{Chloe Chen \& Kangrui Liu}
\date{9/5/2023}

\begin{document}
\maketitle

\hypertarget{use-in-package.}{%
\section{\texorpdfstring{1. Use \texttt{hprice} in \texttt{faraway}
package.}{1. Use  in  package.}}\label{use-in-package.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#prepare data set}
\FunctionTok{library}\NormalTok{(}\StringTok{"faraway"}\NormalTok{)}
\FunctionTok{data}\NormalTok{(}\StringTok{"hprice"}\NormalTok{)}
\FunctionTok{dim}\NormalTok{(hprice)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 324   8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hprice}\SpecialCharTok{$}\NormalTok{homeprice}\OtherTok{\textless{}{-}}\FunctionTok{exp}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{narsp)}\SpecialCharTok{*}\DecValTok{1000}
\end{Highlighting}
\end{Shaded}

\hypertarget{what-are-the-mean-and-the-variance-of-homeprice-what-do-they-mean}{%
\subsection{1) What are the mean and the variance of homeprice? What do
they
mean?}\label{what-are-the-mean-and-the-variance-of-homeprice-what-do-they-mean}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 94411.42
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1583110349
\end{verbatim}

\begin{itemize}
\item
  \begin{enumerate}
  \def\labelenumi{\alph{enumi})}
  \tightlist
  \item
    The mean is \(94411.42\) and the variance is \(1583110349\).\\
  \end{enumerate}
\item
  \begin{enumerate}
  \def\labelenumi{\alph{enumi})}
  \setcounter{enumi}{1}
  \tightlist
  \item
    The terms ``mean'' and ``variance'' refer to the average of a data
    set and the deviation of a data point from the mean, respectively.\\
  \end{enumerate}
\end{itemize}

\hypertarget{construct-a-95-confidence-interval-of-the-average-homeprice.-what-does-the-confidence-interval-imply}{%
\subsection{2) Construct a 95\% confidence interval of the average
homeprice. What does the confidence interval
imply?}\label{construct-a-95-confidence-interval-of-the-average-homeprice.-what-does-the-confidence-interval-imply}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n}\OtherTok{\textless{}{-}}\FunctionTok{dim}\NormalTok{(hprice)[[}\DecValTok{1}\NormalTok{]] }\CommentTok{\# find the number of homeprice}
\NormalTok{samvar}\OtherTok{\textless{}{-}}\FunctionTok{var}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice)}\SpecialCharTok{/}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)  }\CommentTok{\# sampling var }
\NormalTok{samvar}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4901270
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t.score}\OtherTok{\textless{}{-}}\FunctionTok{qt}\NormalTok{(}\AttributeTok{p=}\NormalTok{.}\DecValTok{05}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{, }\AttributeTok{lower.tail=}\NormalTok{F)}
\NormalTok{t.score}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.967336
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lowCI }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice)}\SpecialCharTok{{-}}\NormalTok{t.score}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(samvar)}
\NormalTok{upCI }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice)}\SpecialCharTok{+}\NormalTok{t.score}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(samvar)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(lowCI,upCI))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 90055.97 98766.87
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  hprice$homeprice
## t = 42.711, df = 323, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  90062.70 98760.14
## sample estimates:
## mean of x 
##  94411.42
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The 95\% confidence interval of \(\mu_{homeprice}\) is
  \([90055.97, 98766.87]\)\\
\end{itemize}

\hypertarget{estimate-the-average-homeprice-by-whether-the-mas-was-adjacent-to-a-coastline-noted-in-ajwtr-and-the-standard-errors.}{%
\subsection{3) Estimate the average homeprice by whether the MAS was
adjacent to a coastline, noted in ajwtr, and the standard
errors.}\label{estimate-the-average-homeprice-by-whether-the-mas-was-adjacent-to-a-coastline-noted-in-ajwtr-and-the-standard-errors.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{subset1 }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(hprice, hprice}\SpecialCharTok{$}\NormalTok{ajwtr }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}\CommentTok{\# yes}
\NormalTok{subset2 }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(hprice, hprice}\SpecialCharTok{$}\NormalTok{ajwtr }\SpecialCharTok{==} \DecValTok{0}\NormalTok{)}\CommentTok{\# no}
\NormalTok{mean1 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(subset1}\SpecialCharTok{$}\NormalTok{homeprice)}
\NormalTok{mean2 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(subset2}\SpecialCharTok{$}\NormalTok{homeprice)}
\NormalTok{se1 }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(subset1}\SpecialCharTok{$}\NormalTok{homeprice)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(subset1))}
\NormalTok{se2 }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(subset2}\SpecialCharTok{$}\NormalTok{homeprice)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(subset2))}
\end{Highlighting}
\end{Shaded}

\hypertarget{test-the-difference-in-homeprice-between-coastline-msas-and-non-coastline-msas.-clearly-state-the-formula-for-the-hypothesis-the-test-method-and-your-rationale-for-selecting-the-method.-what-do-you-conclude-about-the-hypothesis}{%
\subsection{4) Test the difference in homeprice between coastline MSAs
and non-coastline MSAs. Clearly state the formula for the hypothesis,
the test method and your rationale for selecting the method. What do you
conclude about the
hypothesis?}\label{test-the-difference-in-homeprice-between-coastline-msas-and-non-coastline-msas.-clearly-state-the-formula-for-the-hypothesis-the-test-method-and-your-rationale-for-selecting-the-method.-what-do-you-conclude-about-the-hypothesis}}

\begin{itemize}
\tightlist
\item
  Step1: Check means and variances\\
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 载入程辑包：'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hprice}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(ajwtr)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{m=}\FunctionTok{mean}\NormalTok{(homeprice),}
            \AttributeTok{v=}\FunctionTok{var}\NormalTok{(homeprice))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   ajwtr       m           v
##   <fct>   <dbl>       <dbl>
## 1 0      82389.  285315565.
## 2 1     111243. 2926428411.
\end{verbatim}

\begin{itemize}
\item
  \(\mu_{ajwtr=0}=\hat{\bar{y}}_{ajwtr=0}=82388.89\) and
  \(\sigma^2_{ajwtr=0}=s^2_{ajwtr=0}=285315565\)
\item
  \(\mu_{ajwtr=1}=\hat{\bar{y}}_{ajwtr=1}=111242.96\) and
  \(\sigma^2_{ajwtr=1}=s^2_{ajwtr=1}=2926428411\)
\item
  Step2: Test equal variance ( with F test)\\
  Corresponding hypothesis:
  \(H_0:\sigma^2_{ajwtr=0}=\sigma^2_{ajwtr=1}\)
  vs.~\(H_A:\sigma^2_{ajwtr=0}\neq\sigma^2_{ajwtr=1}.\)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var.test}\NormalTok{(homeprice }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ajwtr, hprice, }\AttributeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  homeprice by ajwtr
## F = 0.097496, num df = 188, denom df = 134, p-value < 2.2e-16
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.07088604 0.13297389
## sample estimates:
## ratio of variances 
##         0.09749617
\end{verbatim}

\begin{itemize}
\item
  The range of 95 percent confidence interval is
  \([0.07088604,0.13297389]\), and the ratio of variances is
  \(0.09749617\). Therefore, We conclude that
  \(H_0:\sigma^2_{ajwtr=0}=\sigma^2_{ajwtr=1}\) does not hold.
\item
  Step 3: Conduct proper testing(t-test)\\
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(homeprice }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ajwtr, hprice, }\AttributeTok{var.equal=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{conf.int =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  homeprice by ajwtr
## t = -5.9922, df = 152.79, p-value = 1.43e-08
## alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
## 95 percent confidence interval:
##  -38367.19 -19340.96
## sample estimates:
## mean in group 0 mean in group 1 
##        82388.89       111242.96
\end{verbatim}

\begin{itemize}
\tightlist
\item
  We reject \(H_0: \mu_{=1}=\mu_{=0}\), meaning that the homeprice is
  not the same for those living on different coastlines.
\end{itemize}

\hypertarget{estimate-the-pearson-correlation-coefficient-between-homeprice-and-per-capita-income-of-the-msa-of-a-given-year-noted-in-ypc.}{%
\subsection{5) Estimate the Pearson correlation coefficient between
homeprice and per capita income of the MSA of a given year, noted in
ypc.}\label{estimate-the-pearson-correlation-coefficient-between-homeprice-and-per-capita-income-of-the-msa-of-a-given-year-noted-in-ypc.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice, hprice}\SpecialCharTok{$}\NormalTok{ypc, }\AttributeTok{method=}\StringTok{"pearson"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7437474
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The Pearson correlation coefficient between homeprice and ypc is
  \(0.7437474\).
\end{itemize}

\hypertarget{test-whether-the-correlation-coefficient-between-homeprice-and-ypc-is-0-or-not.-clearly-state-the-hypothesis-including-the-formula.-what-do-you-conclude}{%
\subsection{6) Test whether the correlation coefficient between
homeprice and ypc is 0 or not. Clearly state the hypothesis including
the formula. What do you
conclude?}\label{test-whether-the-correlation-coefficient-between-homeprice-and-ypc-is-0-or-not.-clearly-state-the-hypothesis-including-the-formula.-what-do-you-conclude}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor.test}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice, hprice}\SpecialCharTok{$}\NormalTok{ypc, }\AttributeTok{method=}\StringTok{"pearson"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  hprice$homeprice and hprice$ypc
## t = 19.965, df = 322, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6907661 0.7887854
## sample estimates:
##       cor 
## 0.7437474
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Corresponding hypothesis: \(H_0:\rho=0\) vs.~\(H_A:\rho\neq0\).
\item
  \(\bar\rho=0.7437474\), and 95\% CI is \([0.6907661,0.7887854]\), So
  reject \(H_0\).
\end{itemize}

\hypertarget{can-you-say-that-per-capita-income-has-an-effect-on-the-home-sales-price-using-the-results-from-6-why-or-why-not}{%
\subsection{7) Can you say that per capita income has an effect on the
home sales price using the results from \#6)? Why or why
not?}\label{can-you-say-that-per-capita-income-has-an-effect-on-the-home-sales-price-using-the-results-from-6-why-or-why-not}}

\begin{itemize}
\tightlist
\item
  The fact that two variables A and B have a significant correlation
  coefficient does not imply that A has a causal effect on B.
  Correlation measures the strength and direction of a linear
  relationship between two variables, but it does not establish
  causation. Causation would require further research or causal
  inference methods to determine whether one variable directly
  influences the other. Therefore, significant correlation alone does
  not imply a causal relationship.
\end{itemize}

\hypertarget{test-the-normality-of-homeprice.-would-this-test-result-change-your-responses-to-1-to-7-why-or-why-not}{%
\subsection{8) Test the normality of homeprice. Would this test result
change your responses to \#1) to 7)? Why or why
not?}\label{test-the-normality-of-homeprice.-would-this-test-result-change-your-responses-to-1-to-7-why-or-why-not}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{ggplot}\NormalTok{(hprice, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{homeprice)) }\SpecialCharTok{+} \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth=}\DecValTok{2200}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project-1-3_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice, }\AttributeTok{main=}\StringTok{"hprice"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"y\_\{i:n\}"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"m\_\{i:n\}"}\NormalTok{) }
\FunctionTok{qqline}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project-1-3_files/figure-latex/unnamed-chunk-10-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(hprice}\SpecialCharTok{$}\NormalTok{homeprice)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  hprice$homeprice
## W = 0.7327, p-value < 2.2e-16
\end{verbatim}

\begin{itemize}
\tightlist
\item
  In Shapiro-Wilk normality test, p-value \textless{} 0.05, and from the
  histogram, as well as the qq-plot, \texttt{homeprice} does not appear
  to follow a normal distribution.But this wouldn't change the responses
  to the previous questions, because this still make sense with a
  sufficiently large sample(N=324), according to CLT.\\
\end{itemize}

\end{document}
